---

- name: Dev env setup
  hosts: local

  tasks:

  - name: Tap caskroom/fonts for powerline fonts
    homebrew_tap:
      name: homebrew/cask-fonts

  # - name: Tap caskroom/versions for edge versions
  #   homebrew_tap:
  #     name: homebrew/cask-versions

  - name: Install fonts
    homebrew_cask:
      name: font-firacode-nerd-font

  - name: Install neovim
    homebrew:
      name: neovim

  - name: Install other utilities
    homebrew: name={{ item }}
    with_items:
      - ruby
      - rbenv
      - zsh-syntax-highlighting
      - ctags
      - fortune
      - node
      - diff-so-fancy

  - name: Install bat which is a better alternative for cat
    homebrew:
      name: bat

  - name: Install htop which is a better alternative for top
    homebrew:
      name: htop

  - name: Install fd which is a better alternative for find
    homebrew:
      name: fd

  - name: Install tldr which is a better alternative for help
    homebrew:
      name: tldr

  - name: Add node support for neovim
    npm:
      name: neovim
      global: yes

  - name: Add ruby support for neovim
    gem:
      name: neovim

  - name: Add python support for neovim
    pip:
      name: neovim
      executable: pip3

  - name: Browse gem source code with vim
    gem:
      name: 'gem-ctags'

  - name: Remove the default zshrc file
    file:
      path: ~/.zshrc
      state: absent

  - name: Create config directory for neovim
    file:
      path: ~/.config/nvim/
      state: directory

  - name: Symlink the config files for zsh and neovim
    file:
      src: "$HOME/dotfiles-1/.zshrc"
      dest: "$HOME/.zshrc"
      state: link
      force: yes

  - name: Symlink the cobalt theme to oh my zsh
    file:
      src: "$HOME/dotfiles-1/cobalt2.zsh-theme"
      dest: "$ZSH/themes/cobalt2.zsh-theme"
      state: link
      force: yes

  - name: Clone zsh-autosuggestions to oh-my-zsh
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "$ZSH/custom/plugins/zsh-autosuggestions"

  - name: Clone zsh-completions to oh-my-zsh
    git:
      repo: https://github.com/zsh-users/zsh-completions
      dest: "$ZSH/custom/plugins/zsh-completions"

  - name: get the afterglow themeto home directory
    get_url:
      url: https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Afterglow.itermcolors
      dest: "$HOME/Afterglow.itermcolors"

  - name: Symlink the neovim config files
    file:
      src: "$HOME/dotfiles-1/nvim/init.vim"
      dest: "$HOME/.config/nvim/init.vim"
      state: link
      force: yes

  - name: Symlink the neovim config files dealing with general settings
    file:
      src: "$HOME/dotfiles-1/nvim/general.vim"
      dest: "$HOME/.config/nvim/general.vim"
      state: link
      force: yes

  - name: Symlink the part of neovim config dealing with plugins
    file:
      src: "$HOME/dotfiles-1/nvim/plugins.vim"
      dest: "$HOME/.config/nvim/plugins.vim"
      state: link
      force: yes

  - name: Symlink the part of neovim config dealing with keys binding
    file:
      src: "$HOME/dotfiles-1/nvim/keys.vim"
      dest: "$HOME/.config/nvim/keys.vim"
      state: link
      force: yes

  - name: Symlink the part of neovim config dealing with custom commands
    file:
      src: "$HOME/dotfiles-1/nvim/custom_commands.vim"
      dest: "$HOME/.config/nvim/custom_commands.vim"
      state: link
      force: yes

  - name: Symlink snippets for rails
    file:
      src: "$HOME/dotfiles-1/nvim/custom_snippets/rails.snippets"
      dest: "$HOME/.config/nvim/custom_snippets/rails.snippets"
      state: link
      force: yes


  - name: Symlink the neovim colorscheme
    file:
      src: "$HOME/dotfiles-1/nvim/colors"
      dest: "$HOME/.config/nvim/colors"
      state: link
      force: yes

  - name: Initialize z on shell init
    lineinfile: dest=~/.zshrc line=". `brew --prefix`/etc/profile.d/z.sh"

  - name: Alias cat for bat
    lineinfile: dest=~/.zshrc line="alias cat='bat'"

  - name: Alias man for tldr
    lineinfile: dest=~/.zshrc line="alias help='tldr'"

  - name: Symlink the gitignore file
    file:
      src: "$HOME/dotfiles-1/.gitignore"
      dest: "$HOME/.gitignore_global"
      state: link
      force: yes

  - name: Symlink the git_template directory
    file:
      src: "$HOME/dotfiles-1/.git_template"
      dest: "$HOME/.git_template"
      state: link
      force: yes

  - name: Symlink the git config file
    file:
      src: "$HOME/dotfiles-1/.gitconfig"
      dest: "$HOME/.gitconfig"
      state: link
      force: yes

  - name: Symlink the short dir alias file
    file:
      src: "$HOME/dotfiles-1/short-dir.zsh"
      dest: "$ZSH/custom/short-dir.zsh"
      state: link
      force: yes

  - name: Symlink the docker alias file
    file:
      src: "$HOME/dotfiles-1/docker-rails.zsh"
      dest: "$ZSH/custom/docker-rails.zsh"
      state: link
      force: yes
