#!/usr/bin/env ruby

unless system("/usr/local/bin/brew -v")
  puts "Installing homebrew..."
  system %{ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"}
end

unless system("/usr/local/bin/ansible --version")
  puts "Installing ansible..."
  system "brew install ansible"
end

system "cd /tmp/jumpstart && ansible-playbook osx.yml -K -vvvv"
